const { app } = require('./app')
const positionModule = require('./position')
const companyModule = require('./company')
const userModule = require('./user')
const resumeModule = require('./resume')
const deliveryModule = require('./delivery')

positionModule.getPosition()
positionModule.getAllPosition()
positionModule.getPositionById()
positionModule.getPositionInfo()
positionModule.insertPosition()
positionModule.delPosition()
positionModule.getSelectPosition()
companyModule.getCompany()
companyModule.getAllCompany()
companyModule.getCompanyById()
companyModule.getSelectCompany()
companyModule.delCompany()
userModule.registry()
userModule.editUser()
userModule.login()
userModule.updateUserCompany()
userModule.getAllUser()
userModule.delUser()
userModule.editPwd()
resumeModule.saveResume()
resumeModule.getResume()
deliveryModule.insertDelivery()
deliveryModule.getDelivery()
deliveryModule.getReceive()
deliveryModule.updateDelivery()

app.listen(8804,'127.0.0.1');
